spring:
  application:
    name: ev-charging-scheduler

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    driver-class-name: org.postgresql.Driver
    username: myuser
    password: secret

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

energidataservice:
  base-url: https://api.energidataservice.dk
  default-zone: DK2

scheduling:
  enabled: true
