spring:
  application:
    name: ev-charging-scheduler

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mydatabase}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

energidataservice:
  base-url: https://api.energidataservice.dk
  default-zone: DK2

scheduling:
  enabled: true

app:
  security:
    username: ${APP_SECURITY_USERNAME}
    password: ${APP_SECURITY_PASSWORD}
